### ISSUE TITLE
enable using dynamic settings in override match condition

### ISSUE THREAD

**Issue by flovntp** [lolautruche/EzCoreExtraBundle#11]
It should be really helpfull to enable dynamic settings in override condition, like : 

``` yaml
ezpublish:
    system:
         site_group:
            location_view:
                 full:
                     my_override_condition:
                         template: "@ezdesign/full/myGenericTemplate.html.twig"
                         match:
                              Id\Location: $locationId;acme$
```

and then, you just have to defined your dynamics settings for all your siteaccess in parameters.yml 

``` yaml
parameters:
      acme.fre.locationId: 123
      acme.en.locationId: 456
```
