### ISSUE TITLE
Make repository services configurable

### ISSUE THREAD

**Issue by lolautruche** [lolautruche/EzCoreExtraBundle#15]
Some eZ repository services are designed to allow settings injection:

* [UserService](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Repository/UserService.php#L76-L82)
* [RoleService](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Repository/RoleService.php#L96-L122)
* [NameSchemaService](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Repository/Helper/NameSchemaService.php)
* [URLAliasService](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Repository/URLAliasService.php#L56-L58)

However there is currently no way to define these settings, except for a few (e.g. anonymous user ID).

It would be nice to expose some semantic configuration for this:

```yaml
ez_core_extra:
    system:
        default:
            repository:
                user:
                    default_placement: 12
                    content_type_id: 4
                    group_id: 3
                    password_hash_type: ~
                    site_name: ez.no
                name_schema:
                    limit: 150
                    sequence: ...
                url_alias:
                    show_all_translations: false
```
