### ISSUE TITLE
pass parameters to ParamProvider via ezpublish.yml

### ISSUE THREAD

**Issue by flovntp** [lolautruche/EzCoreExtraBundle#22]
Add possibility to pass parameter to a paramProvider within an override rules : 

``` 
ezpublish:
    system:
        eng:
            location_view:
                full:
                    site:
                        template: "@ezdesign/full/site.html.twig"
                        params:
                            children: {"provider": "children_provider", "params": { 'contentTypes': { 'brouette', 'casque' } } }
```

This should simplify some children injection
