### ISSUE TITLE
paramProvider not working any more on last eZPlatform

### ISSUE THREAD

**Issue by flovntp** [lolautruche/EzCoreExtraBundle#23]
Since the new QueryType controller has been introduce for override rules in eZ Platform, it's not possible any more to use ParamProvider to inject new variable in a template.
Debugger step by step is well going through paramProvider PHP function but array of variables returned are not taken in account.
```
ezpublish:
    system:
        fre:
            location_view:
                full:
                    site:
                        controller: "ez_query:contentQueryAction"
                        template: "@ezdesign/full/site.html.twig"
                        match:
                            Identifier\ContentType: site
                        params:
                            my_provider: {"provider": "footer_provider"}
                            query:
                                query_type: 'CRParameterProvider:SectionChildren'
                                parameters:
                                    parentLocationId: "@=location.id"
                                    type: ['blog_post']
                                assign_results_to: 'article'
```
In the final template, if we dump my_provider set in the override rule, we get the text of the paramProvider conf.
So, within the site.html.twig template, we've got that result:
```
array:1 [
  "provider" => "footer_provider"
]
```
so, now, paramProvider is not replace by it's returned value from PHP code, but as a text variable.
(And even if not using the QueryType syntax)
