### ISSUE TITLE
Enable autoconfigure for view parameter providers

### ISSUE THREAD

**Issue by lolautruche** [lolautruche/EzCoreExtraBundle#36]
Enable this awesome feature from Symfony 3.3, so that one can register a view parameter provider the following way:

```yaml
services:
    _defaults:
        autoconfigure: true

    Acme\Provider\MyParamProvider: ~
```

This means to:
- Add `$container->registerForAutoconfiguration()` call in `EzCoreExtraExtension` (if Symfony version >= 3.3)
- Remove the `alias` attribute which seem unnecessary
- Use the service name as `alias`
