### ISSUE TITLE
Add expression support in configured view parameters

### ISSUE THREAD

**Issue by lolautruche** [lolautruche/EzCoreExtraBundle#37]
When injecting parameters in views, it would be very handy to be able to use Symfony `ExpressionLanguage`. This would reduce the need to implement a param provider.

## Proposed syntax:

```yaml
ezpublish:
    system:
        site:
            content_view:
                full:
                    my_view:
                        template: '@ezdesign/my_view.html.twig'
                        params:
                            foo:
                                expression: 'some_expression_here'
```

## Variables to expose:
- `content` => current Content
- `location` => current Location
- `contentType` => ContentType of the current content
- `loadContent()` function
- `loadLocation()` function
- `loadContentType()` function
