### ISSUE TITLE
The twig globals variables for a siteaccess not work

### ISSUE THREAD

**Issue by jbcr** [lolautruche/EzCoreExtraBundle#52]
The twig global variable is not available on twig template:

`lolautruche/ez-core-extra-bundle` version `2.2.1`
`ezsystems/ezpublish-kernel` version `6.13.6`

Bundle configuration:

```
ez_core_extra:
    system:
        front_end:
            twig_globals:
                app_name: 'frontend'
```

Twig template:

```
App name: {{ app_name }}
```

Result:

```
The variable app_name is not defined
```
