### ISSUE TITLE
Define Twig Globals for a group of SA

### ISSUE THREAD

**Issue by flovntp** [lolautruche/EzCoreExtraBundle#8]
It is not possible to create twig_globals for a group of siteaccess.

```
ez_core_extra:
    system:
        front_group:
            twig_globals: 
                 foo: bar
```

--> Unable to find variable foo in templates
